# Generated by Django 3.2.13 on 2023-06-26 20:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_iamge',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=users.models.image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 20, 35, 23, 788373, tzinfo=utc)),
        ),
    ]
