# Generated by Django 3.2.13 on 2023-06-26 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230627_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_iamge',
            new_name='user_image',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 20, 41, 14, 515597, tzinfo=utc)),
        ),
    ]
