# Generated by Django 3.2.13 on 2023-06-26 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230627_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 21, 1, 38, 574947, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 21, 1, 38, 574947, tzinfo=utc)),
        ),
    ]
